[versions]
architectury-loom = "1.9-SNAPSHOT"
architectury-plugin = "3.4-SNAPSHOT"
blossom = "1.3.1"
shadow = "8.1.1"

fabric-loader = "0.16.10"

[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }

[plugins]
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
architectury-plugin = { id = "architectury-plugin", version.ref = "architectury-plugin" }

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
