modLoader = "javafml"
loaderVersion = "*"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = "${description}"
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[mixins]]
config = "template-common.mixins.json"

[[mixins]]
config = "template-neoforge.mixins.json"
